### ISSUE TITLE
Docker-compose configuration doesn't work out the box

### ISSUE THREAD

**Issue by mirkoperillo** [BrickSchema/brick-server#25]
Using the default docker-compose configuration the brick-server fails because to many connections to Postgres.
Same situation as here https://github.com/BrickSchema/brick-server/issues/5#issuecomment-884902733

My workaround is setting the `max_connections` parameters for the Postgres instance.

Here the snippet in my `docker-compose.yml`

```
 brickserver-postgres:
     container_name: brickserver-postgres
     image: "jbkoh/brickserver-postgresql:latest"
     command: postgres -c 'max_connections=300'
     environment: # Below secrets should be matched with the information in `configs.json` too.
       - POSTGRES_USER=bricker
       - POSTGRES_PASSWORD=brick-demo
       - POSTGRES_DB=brick
```

the interesting line is:
```
command: postgres -c 'max_connections=300'
```
